server:
      port: 8076
spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mariadb://127.0.0.1:3306/liquibasetest?useLegacyDatetimeCode=false&serverTimezone=UTC&sessionVariables=character_set_client=utf8mb4,character_set_results=utf8mb4,character_set_connection=utf8mb4,collation_connection=utf8mb4_unicode_ci
    username: root
    password: root
logging:
  level:
    org:
      springframework:
        web: DEBUG
        security: DEBUG
springdoc:
  swagger-ui.path: /india-railway-api-docs.html